admin_panel/urls.py
from django.urls import path

from .views import (MainView, AlbumsDataView, GenresDataView,
                    ArtistsDataView, AlbumsDataSearchView, UnconfirmedOrdersDataView,
                    ConfirmedOrdersDataView, UsersBlacklistView)

app_name = 'admin-panel'

urlpatterns = [
    path('', MainView.as_view(), name='main-page'),
    path('albums/', AlbumsDataView.as_view(), name='albums-data'),
    path('albums/search/', AlbumsDataSearchView.as_view(), name='albums-data-search'),
    path('genres/', GenresDataView.as_view(), name='genres-data'),
    path('artists/', ArtistsDataView.as_view(), name='artists-data'),
    path('blacklist/', UsersBlacklistView.as_view(), name='blacklist'),
    path('unconfirmed-orders/', UnconfirmedOrdersDataView.as_view(), name='unconfirmed-orders'),
    path('confirmed-orders/', ConfirmedOrdersDataView.as_view(), name='confirmed-orders'),
]

albums/urls.py
from django.urls import path

from .views import (AlbumListView, AlbumDetailView, AlbumFilterView, AlbumSearchView,
                    AlbumCreateView, AlbumUpdateView, AlbumDeleteView, GenreCreateView,
                    GenreUpdateView, GenreDeleteView, ArtistDeleteView, ArtistCreateView,
                    ArtistUpdateView)

app_name = 'albums'

urlpatterns = [
    # User endpoints (only albums)
    path('', AlbumListView.as_view(), name='albums-list'),
    path('filter/', AlbumFilterView.as_view(), name='albums-filter'),
    path('search/', AlbumSearchView.as_view(), name='albums-search'),
    
    # Admin endpoint (should be before album-detail to avoid errors)
    path('create/', AlbumCreateView.as_view(), name='album-create'),
    path('<pk>/', AlbumDetailView.as_view(), name='album-detail'),
    
    # Admin endpoints

    # Albums
    path('<pk>/update/', AlbumUpdateView.as_view(), name='album-update'),
    path('<pk>/delete/', AlbumDeleteView.as_view(), name='album-delete'),

    # Genres
    path('genres/create/', GenreCreateView.as_view(), name='genre-create'),
    path('genres/<pk>/update/', GenreUpdateView.as_view(), name='genre-update'),
    path('genres/<pk>/delete/', GenreDeleteView.as_view(), name='genre-delete'),

    # Artists
    path('artists/create/', ArtistCreateView.as_view(), name='artist-create'),
    path('artists/<pk>/update/', ArtistUpdateView.as_view(), name='artist-update'),
    path('artists/<pk>/delete/', ArtistDeleteView.as_view(), name='artist-delete'),
]

orders/urls.py
from django.urls import path

from .views import (CartView, cart_item_create_view, cart_item_remove_view,
                    order_create_view, order_pay_view, order_success_pay_view,
                    order_confirm_view, order_discard_view, user_ban_view, user_unban_view)

app_name = 'orders'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/', cart_item_create_view, name='cart-item-create'),
    path('delete/', cart_item_remove_view, name='cart-item-remove'),
    path('users/ban/<str:username>/', user_ban_view, name='user-ban'),
    path('users/unban/<str:username>/', user_unban_view, name='user-unban'),
    path('orders/', order_create_view, name='order-create'),
    path('orders/<int:pk>/pay/', order_pay_view, name='order-pay'),
    path('orders/<int:pk>/confirm/', order_confirm_view, name='order-confirm'),
    path('orders/<int:pk>/discard/', order_discard_view, name='order-discard'),
    path('orders/<int:pk>/pay/success/', order_success_pay_view, name='order-success-pay'),
]

website/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from albums.views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('albums/', include('albums.urls')),
    path('admin-panel/', include('admin_panel.urls')),
    path('cart/', include('orders.urls')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

admin_panel/models.py
from django.db import models

# Create your models here.

albums/models.py
from django.db import models

from .validators import validate_text, validate_release_date


class GenreArtistManager(models.Manager):
    def get_ordered_by_title(self):
        return self.all().order_by('title')


class Artist(models.Model):
    title = models.CharField(max_length=75, validators=[validate_text])

    objects = GenreArtistManager()

    def __str__(self) -> str:
        return self.title


class Genre(models.Model):
    title = models.CharField(max_length=75, validators=[validate_text])
    
    objects = GenreArtistManager()
    
    def __str__(self) -> str:
        return self.title


class Album(models.Model):
    # General fields
    title = models.CharField(max_length=75, validators=[validate_text])
    release_date = models.CharField(max_length=30, blank=True, validators=[validate_release_date])
    duration = models.CharField(max_length=10, blank=True)
    image = models.URLField()    
    tracks = models.JSONField()
    price = models.IntegerField()
    count = models.IntegerField(default=10000)

    # One-to-many fields
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

    # Many-to-many fields
    genres = models.ManyToManyField(Genre, db_table='AlbumsGenres')

    def __str__(self) -> str:
        return self.title 
    

albums/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField

from .models import Album, Genre, Artist
from orders.models import CustomUser


class AlbumModelForm(forms.ModelForm):
    duration = forms.DurationField(widget=forms.TextInput(attrs={'placeholder': ''}))
    tracks = forms.CharField(label="Tracks",
                             widget=forms.Textarea())
    genres = forms.ModelMultipleChoiceField(
            widget=forms.SelectMultiple(),
            queryset=Genre.objects.get_ordered_by_title(),
            required=True,
        )
    artist = forms.ModelChoiceField(queryset=Artist.objects.get_ordered_by_title(),
                                    required=True)

    class Meta:
        model = Album
        fields = (
            'title',
            'release_date',
            'duration',
            'image',
            'tracks',
            'price',
            'genres',
            'artist',
        )

    def clean_title(self):
        title = self.cleaned_data.get('title')
        album = Album.objects.filter(title__iexact=title).exists()
        if album:
            raise forms.ValidationError('Альбом з такою назвою вже існує')
        return title

    def clean(self):
        cleaned_data = super().clean()

        # Convert tracks string into list
        tracks = cleaned_data.get('tracks')
        tracks_list = [track for track in tracks.split('\r\n')]
        cleaned_data['tracks'] = tracks_list

        return cleaned_data


class GenreModelForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ['title']

    def clean_title(self):
        title = self.cleaned_data.get('title')
        album = Genre.objects.filter(title__iexact=title).exists()
        if album:
            raise forms.ValidationError('Жанр з такою назвою вже існує')
        return title


class ArtistModelForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ['title']

    def clean_title(self):
        title = self.cleaned_data.get('title')
        album = Artist.objects.filter(title__iexact=title).exists()
        if album:
            raise forms.ValidationError('Артист з таким ім\'ям уже існує')
        return title


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username",)
        field_classes = {'username': UsernameField}

    # def clean_username(self):
    #     username = self.cleaned_data.get("username")
    #     if CustomUser.objects.filter(username=username).exists():
    #         raise forms.ValidationError(
    #             "This username is already in use"
    #         )
    #     return username

admin_panel/views.py
from django.views import generic

from albums.models import Album, Genre, Artist
from albums.views import AlbumSearchView
from albums.mixins import AdminRequiredMixin
from orders.models import Order, CustomUser


class MainView(AdminRequiredMixin, generic.TemplateView):
    template_name = 'admin_panel/main.html'


class AlbumsDataView(AdminRequiredMixin, generic.ListView):
    template_name = 'admin_panel/albums.html'
    queryset = Album.objects.all()
    context_object_name = 'albums'
    
    paginate_by = 20


class AlbumsDataSearchView(AdminRequiredMixin, AlbumSearchView):
    template_name = 'admin_panel/albums.html'
    

class GenresDataView(AdminRequiredMixin, generic.ListView):
    template_name = 'admin_panel/genres.html'
    queryset = Genre.objects.get_ordered_by_title()
    context_object_name = 'genres'


class ArtistsDataView(AdminRequiredMixin, generic.ListView):
    template_name = 'admin_panel/artists.html'
    queryset = Artist.objects.get_ordered_by_title()
    context_object_name = 'artists'


class UsersBlacklistView(AdminRequiredMixin, generic.ListView):
    template_name = 'admin_panel/blacklist.html'
    queryset = CustomUser.objects.filter(is_banned=True)
    context_object_name = 'users'


class UnconfirmedOrdersDataView(AdminRequiredMixin, generic.ListView):
    template_name = 'admin_panel/unconfirmed_orders.html'
    queryset = Order.objects.filter(is_confirmed=False)
    context_object_name = 'orders'


class ConfirmedOrdersDataView(AdminRequiredMixin, generic.ListView):
    template_name = 'admin_panel/confirmed_orders.html'
    queryset = Order.objects.filter(is_confirmed=True)
    context_object_name = 'orders'

albums/views.py
from typing import Any

from django.db.models.query import QuerySet
from django.urls import reverse
from django.views import generic
from django.db.models import Q

from .models import Album, Genre, Artist
from .forms import AlbumModelForm, ArtistModelForm, GenreModelForm, CustomUserCreationForm
from .mixins import ArtistsGenresDataMixin, GetModelNameMixin, AdminRequiredMixin
from orders.models import CartItem, Order


# Additional view to add context data to filter sidebar
# User views

class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def form_valid(self, form):
        response = super().form_valid(form)
        return response

    def get_success_url(self):
        return reverse("login")


class AlbumListView(ArtistsGenresDataMixin, generic.ListView):
    model = Album
    template_name = 'albums/albums_list.html'
    context_object_name = 'albums'


class AlbumDetailView(generic.DetailView):
    model = Album
    template_name = 'albums/album_detail.html'
    context_object_name = 'album'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_item'] = CartItem.objects.filter(user=self.request.user, album__pk=context['album'].pk)
        return context


class AlbumFilterView(ArtistsGenresDataMixin, generic.ListView):
    context_object_name = 'albums'
    template_name = 'albums/albums_list.html'

    def get_queryset(self) -> QuerySet[Any]:

        # Retrieving 'True' checkboxes' values from fort GET request
        genres_filters = self.request.GET.getlist("genre")
        artist_filters = self.request.GET.getlist("artist")
        decade_filters = self.request.GET.getlist("decades")

        sort_query = self.request.GET.get('sort_by')

        # Condition to prevent hand-written query parametrs in link
        allowed_sort_queries = ['price', '-price', 'release_date', '-release_date']
        if sort_query not in allowed_sort_queries:
            sort_query = None

        kwargs = {}
        if genres_filters: 
            kwargs["genres__title__in"] = genres_filters

        if artist_filters:
            kwargs["artist__title__in"] = artist_filters
        
        # if decade_filters:
        #     kwargs["release_date__range"] =  (decade_filters[0], int(decade_filters[0]) + 9)

        args = []

        # Multiple decades filtering
        if decade_filters:
            q = Q()
            for decade in decade_filters:
                start_year = decade
                end_year = int(decade) + 9
                q |= Q(release_date__range=(start_year, end_year))
                
            args.append(q) 

        print(args)
        print(kwargs)
        album = Album.objects.filter(
            *args,
            **kwargs).order_by('pk' if not sort_query else sort_query).distinct()
        return album


class AlbumSearchView(ArtistsGenresDataMixin, generic.ListView):
    model = Album
    context_object_name = 'albums'
    template_name = 'albums/albums_list.html'
    
    def get_queryset(self):
        query = self.request.GET.get("q")

        object_list = Album.objects.filter(
            Q(title__icontains=query) |
            Q(artist__title__icontains=query)
            ).order_by('artist', 'title')
        
        return object_list
    
# Admin views


# Albums
class AlbumCreateView(AdminRequiredMixin, GetModelNameMixin, generic.CreateView):
    template_name = "albums/album_create.html"
    form_class = AlbumModelForm
    
    def get_success_url(self):
        return reverse("admin-panel:albums-data")


class AlbumDeleteView(AdminRequiredMixin, GetModelNameMixin, generic.DeleteView):
    template_name = "albums/album_delete.html"
    model = Album
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:albums-data")


class AlbumUpdateView(AdminRequiredMixin, GetModelNameMixin, generic.UpdateView):
    template_name = "albums/album_update.html"
    form_class = AlbumModelForm
    model = Album
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:albums-data")


# Genres
class GenreCreateView(AdminRequiredMixin, GetModelNameMixin, generic.CreateView):
    template_name = "albums/album_create.html"
    form_class = GenreModelForm
    
    def get_success_url(self):
        return reverse("admin-panel:genres-data")


class GenreDeleteView(AdminRequiredMixin, GetModelNameMixin, generic.DeleteView):
    template_name = "albums/album_delete.html"
    model = Genre
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:genres-data")


class GenreUpdateView(AdminRequiredMixin, GetModelNameMixin, generic.UpdateView):
    template_name = "albums/album_update.html"
    form_class = GenreModelForm
    model = Genre
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:genres-data")


# Artists
class ArtistCreateView(AdminRequiredMixin, GetModelNameMixin, generic.CreateView):
    template_name = "albums/album_create.html"
    form_class = ArtistModelForm
    
    def get_success_url(self):
        return reverse("admin-panel:artists-data")


class ArtistDeleteView(AdminRequiredMixin, GetModelNameMixin, generic.DeleteView):
    template_name = "albums/album_delete.html"
    model = Artist
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:artists-data")


class ArtistUpdateView(AdminRequiredMixin, GetModelNameMixin, generic.UpdateView):
    template_name = "albums/album_update.html"
    form_class = ArtistModelForm
    model = Artist
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:artists-data")
    

admin_panel/templates/admin_panel/albums.html
{% extends 'base.html' %}

{% block content%}
<div id="albums-page">
  <h1>Albums</h1>

  <form action="{% url 'admin-panel:albums-data-search' %}" method="get">
    <input type="text" name="q">
    <button type="submit">Search</button>
  </form>

  <a href="{% url 'albums:album-create' %}"><button id="create-album">Create new album</button></a>

  <table>
    <tr>
      <th>Title</th>
      <th>Artist</th>
      <th>Released</th>
      <th>Image</th>
      <th>Duration</th>
      <th>Tracks</th>
      <th>Genres</th>
      <th>Price</th>
      <th></th>
      <th></th>
    </tr>
    {% for album in albums %}
    <tr>
      <td class="title"><a href="{% url 'albums:album-detail' album.pk %}">"{{ album.title }}"</a></td>
      <td class="artist">{{ album.artist }}</td>
      <td class="release-date">{{ album.release_date }}</td>
      <td class="image"><img src="{{ album.image }}"></td>
      <td class="duration">{{ album.duration }}</td>
      <td class="tracks">
        {% for track in album.tracks%}
        "{{track}}"<br>
        {% endfor %}
      </td>
      <td class="genres">
        {% for genre in album.genres.all %}
        {{genre.title}}<br>
        {% endfor %}
      </td>
      <td class="price">{{ album.price }}.00 UAH</td>
      <td class="update-btn"><a href="{% url 'albums:album-update' album.pk %}"><button>Update</button></a></td>
      <td class="delete-btn"><a href="{% url 'albums:album-delete' album.pk %}"><button>Delete</button></a></td>
    </tr>
    {% endfor %}
  </table>

  <div id="pagination">
    {% include 'includes/pagination.html' %}
  </div>

</div>{% endblock content %}

admin_panel/templates/admin_panel/artists.html
{% extends 'base.html' %}

{% block content%}

<div id="artists-page">
    <h1>Artists</h1>
    <table>
        <a href="{% url 'albums:artist-create' %}"><button id="create-artist">Create new artist</button></a>
        {% for artist in artists %}
        <tr>
            <td class="title">{{ artist.title }}</td>
            <td class="update-btn"><a href="{% url 'albums:artist-update' artist.pk %}"><button>Update</button></a></td>
            <td class="delete-btn"><a href="{% url 'albums:artist-delete' artist.pk %}"><button>Delete</button></a></td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock content %}

admin_panel/templates/admin_panel/banned_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div id="banned-page">
    <h1>You're banned on this website :&#40;</h1>
    <img src="{% static 'images/banned.gif' %}" alt="">
</div>
{% endblock content %}

admin_panel/templates/admin_panel/blacklist.html
{% extends 'base.html' %}

{% block content%}
<div id="blacklist-page">
    <h1>Blacklist</h1>

    <table>
        {% for user in users %}
        <tr>
            <td class="user">"{{user.username}}"</td>
            <td class="unban">
                <form action="{% url 'orders:user-unban' user.username %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Unban</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock content %}

admin_panel/templates/admin_panel/confirmed_orders.html
{% extends 'base.html' %}

{% block content%}
<div id="confirmed-orders-page">
    <h1>Confirmed orders</h1>
    <table>
        <tr>
            <th>User</th>
            <th>Total price</th>
            <th>Ordered albums</th>
            <th>Time</th>
        </tr>
        {% for order in orders %}
        <tr>
            <td class="username">{{ order.user.username }}</td>
            <td class="total-price">{{ order.total_price }}.00 UAH</td>
            <td class="albums">
                {% for album in order.albums.all %}
                {{ album.title }}<br>
                {% endfor %}
            </td>
            <td class="datetime">{{ order.created_at }} </td>
        </tr>
        {% endfor %}
    </table>

    <div id="pagination">
        {% include 'includes/pagination.html' %}
    </div>

</div>
{% endblock content %}

admin_panel/templates/admin_panel/genres.html
{% extends 'base.html' %}

{% block content%}

<div id="genres-page">
    <h1>Genres</h1>

    <a href="{% url 'albums:genre-create' %}"><button id="create-genre">Create new genre</button></a>

    <table>
        {% for genre in genres %}
        <tr>
            <td class="title">"{{ genre.title }}"</td>
            <td class="update-btn"><a href="{% url 'albums:genre-update' genre.pk %}"><button>Update</button></a></td>
            <td class="delete-btn"><a href="{% url 'albums:genre-delete' genre.pk %}"><button>Delete</button></a></td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endblock content %}

admin_panel/templates/admin_panel/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div id="admin-panel-main-page">
    <h1>Welcome to the admin-panel!</h1>
    <img src="{% static 'images/admin.gif' %}" alt="">
    <div id="panel">
        <a href="{% url 'admin-panel:albums-data' %}"><button>Albums</button></a>
        <a href="{% url 'admin-panel:artists-data' %}"><button>Artists</button></a>
        <a href="{% url 'admin-panel:genres-data' %}"><button>Genres</button></a>
        <a href="{% url 'admin-panel:unconfirmed-orders' %}"><button>Unconfirmed orders</button></a>
        <a href="{% url 'admin-panel:confirmed-orders' %}"><button>Confirmed orders</button></a>
        <a href="{% url 'admin-panel:blacklist' %}"><button>Blacklist</button></a>
    </div>
</div>{% endblock content %}

admin_panel/templates/admin_panel/unconfirmed_orders.html
{% extends 'base.html' %}

{% block content%}
<div id="unconfirmed-orders-page">
        <h1>Unconfirmed orders data</h1>
        <div>
            <table>
                <tr>
                    <th>User</th>
                    <th>Total price</th>
                    <th>Paid</th>
                    <th>Ordered albums</th>
                    <th>Time</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                {% for order in orders %}
                <tr>
                    <td>{{ order.user.username }}</td>
                    <td>{{ order.total_price }} грн.</td>
                    <td>{{order.is_paid}}</td>
                    <td>
                        {% for album in order.albums.all %}
                            {{ album.title }}<br>
                            {% endfor %}
                    </td>
                    <td>{{ order.created_at }} </td>
                    <td class="confirm">
                        <form action="{% url 'orders:order-confirm' order.pk %}" method="post">
                        {% csrf_token %}
                        <button {% if not order.is_paid or order.user.is_banned %}
                                disabled=""
                                {% endif %}
                        >Confirm order</button>
                        </form>
                    </td>
                    <td class="discard">
                        <form action="{% url 'orders:order-discard' order.pk %}" method="post">
                            {% csrf_token %}
                            <button {% if order.is_paid  %}
                            disabled=""
                            {% endif %}>
                                Discard order
                            </button>
                        </form>
                    </td>
                    <td class="ban">
                        <form action="{% url 'orders:user-ban' order.user.username %}" method="post">
                        {% csrf_token %}
                        <button {% if order.user == request.user or order.user.is_banned or order.is_paid%}
                        disabled=""
                        {% endif %}>
                            Ban user
                        </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}        
            </table>
        </div>
        
        <div>
            {% include 'includes/pagination.html' %}
        </div>
    
</div>
{% endblock content %}