albums/urls.py
from django.urls import path

from .views import (AlbumListView, AlbumDetailView, AlbumFilterView, AlbumSearchView,
                    AlbumCreateView, AlbumUpdateView, AlbumDeleteView, GenreCreateView,
                    GenreUpdateView, GenreDeleteView, ArtistDeleteView, ArtistCreateView,
                    ArtistUpdateView)

app_name = 'albums'

urlpatterns = [
    # User endpoints (only albums)
    path('', AlbumListView.as_view(), name='albums-list'),
    path('filter/', AlbumFilterView.as_view(), name='albums-filter'),
    path('search/', AlbumSearchView.as_view(), name='albums-search'),
    
    # Admin endpoint (should be before album-detail to avoid errors)
    path('create/', AlbumCreateView.as_view(), name='album-create'),
    path('<pk>/', AlbumDetailView.as_view(), name='album-detail'),
    
    # Admin endpoints

    # Albums
    path('<pk>/update/', AlbumUpdateView.as_view(), name='album-update'),
    path('<pk>/delete/', AlbumDeleteView.as_view(), name='album-delete'),

    # Genres
    path('genres/create/', GenreCreateView.as_view(), name='genre-create'),
    path('genres/<pk>/update/', GenreUpdateView.as_view(), name='genre-update'),
    path('genres/<pk>/delete/', GenreDeleteView.as_view(), name='genre-delete'),

    # Artists
    path('artists/create/', ArtistCreateView.as_view(), name='artist-create'),
    path('artists/<pk>/update/', ArtistUpdateView.as_view(), name='artist-update'),
    path('artists/<pk>/delete/', ArtistDeleteView.as_view(), name='artist-delete'),
]

orders/urls.py
from django.urls import path

from .views import (CartView, cart_item_create_view, cart_item_remove_view,
                    order_create_view, order_pay_view, order_success_pay_view,
                    order_confirm_view, order_discard_view, user_ban_view, user_unban_view)

app_name = 'orders'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/', cart_item_create_view, name='cart-item-create'),
    path('delete/', cart_item_remove_view, name='cart-item-remove'),
    path('users/ban/<str:username>/', user_ban_view, name='user-ban'),
    path('users/unban/<str:username>/', user_unban_view, name='user-unban'),
    path('orders/', order_create_view, name='order-create'),
    path('orders/<int:pk>/pay/', order_pay_view, name='order-pay'),
    path('orders/<int:pk>/confirm/', order_confirm_view, name='order-confirm'),
    path('orders/<int:pk>/discard/', order_discard_view, name='order-discard'),
    path('orders/<int:pk>/pay/success/', order_success_pay_view, name='order-success-pay'),
]

website/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from albums.views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('albums/', include('albums.urls')),
    path('admin-panel/', include('admin_panel.urls')),
    path('cart/', include('orders.urls')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

albums/models.py
from django.db import models

from .validators import validate_text, validate_release_date


class GenreArtistManager(models.Manager):
    def get_ordered_by_title(self):
        return self.all().order_by('title')


class Artist(models.Model):
    title = models.CharField(max_length=75, validators=[validate_text])

    objects = GenreArtistManager()

    def __str__(self) -> str:
        return self.title


class Genre(models.Model):
    title = models.CharField(max_length=75, validators=[validate_text])
    
    objects = GenreArtistManager()
    
    def __str__(self) -> str:
        return self.title


class Album(models.Model):
    # General fields
    title = models.CharField(max_length=75, validators=[validate_text])
    release_date = models.CharField(max_length=30, blank=True, validators=[validate_release_date])
    duration = models.CharField(max_length=10, blank=True)
    image = models.URLField()    
    tracks = models.JSONField()
    price = models.IntegerField()
    count = models.IntegerField(default=10000)

    # One-to-many fields
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

    # Many-to-many fields
    genres = models.ManyToManyField(Genre, db_table='AlbumsGenres')

    def __str__(self) -> str:
        return self.title 
    

albums/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField

from .models import Album, Genre, Artist
from orders.models import CustomUser


class AlbumModelForm(forms.ModelForm):
    duration = forms.DurationField(widget=forms.TextInput(attrs={'placeholder': ''}))
    tracks = forms.CharField(label="Tracks",
                             widget=forms.Textarea())
    genres = forms.ModelMultipleChoiceField(
            widget=forms.SelectMultiple(),
            queryset=Genre.objects.get_ordered_by_title(),
            required=True,
        )
    artist = forms.ModelChoiceField(queryset=Artist.objects.get_ordered_by_title(),
                                    required=True)

    class Meta:
        model = Album
        fields = (
            'title',
            'release_date',
            'duration',
            'image',
            'tracks',
            'price',
            'genres',
            'artist',
        )

    def clean_title(self):
        title = self.cleaned_data.get('title')
        album = Album.objects.filter(title__iexact=title).exists()
        if album:
            raise forms.ValidationError('Альбом з такою назвою вже існує')
        return title

    def clean(self):
        cleaned_data = super().clean()

        # Convert tracks string into list
        tracks = cleaned_data.get('tracks')
        tracks_list = [track for track in tracks.split('\r\n')]
        cleaned_data['tracks'] = tracks_list

        return cleaned_data


class GenreModelForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ['title']

    def clean_title(self):
        title = self.cleaned_data.get('title')
        album = Genre.objects.filter(title__iexact=title).exists()
        if album:
            raise forms.ValidationError('Жанр з такою назвою вже існує')
        return title


class ArtistModelForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ['title']

    def clean_title(self):
        title = self.cleaned_data.get('title')
        album = Artist.objects.filter(title__iexact=title).exists()
        if album:
            raise forms.ValidationError('Артист з таким ім\'ям уже існує')
        return title


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username",)
        field_classes = {'username': UsernameField}

    # def clean_username(self):
    #     username = self.cleaned_data.get("username")
    #     if CustomUser.objects.filter(username=username).exists():
    #         raise forms.ValidationError(
    #             "This username is already in use"
    #         )
    #     return username

albums/views.py
from typing import Any

from django.db.models.query import QuerySet
from django.urls import reverse
from django.views import generic
from django.db.models import Q

from .models import Album, Genre, Artist
from .forms import AlbumModelForm, ArtistModelForm, GenreModelForm, CustomUserCreationForm
from .mixins import ArtistsGenresDataMixin, GetModelNameMixin, AdminRequiredMixin
from orders.models import CartItem, Order


# Additional view to add context data to filter sidebar
# User views

class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def form_valid(self, form):
        response = super().form_valid(form)
        return response

    def get_success_url(self):
        return reverse("login")


class AlbumListView(ArtistsGenresDataMixin, generic.ListView):
    model = Album
    template_name = 'albums/albums_list.html'
    context_object_name = 'albums'


class AlbumDetailView(generic.DetailView):
    model = Album
    template_name = 'albums/album_detail.html'
    context_object_name = 'album'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_item'] = CartItem.objects.filter(user=self.request.user, album__pk=context['album'].pk)
        return context


class AlbumFilterView(ArtistsGenresDataMixin, generic.ListView):
    context_object_name = 'albums'
    template_name = 'albums/albums_list.html'

    def get_queryset(self) -> QuerySet[Any]:

        # Retrieving 'True' checkboxes' values from fort GET request
        genres_filters = self.request.GET.getlist("genre")
        artist_filters = self.request.GET.getlist("artist")
        decade_filters = self.request.GET.getlist("decades")

        sort_query = self.request.GET.get('sort_by')

        # Condition to prevent hand-written query parametrs in link
        allowed_sort_queries = ['price', '-price', 'release_date', '-release_date']
        if sort_query not in allowed_sort_queries:
            sort_query = None

        kwargs = {}
        if genres_filters: 
            kwargs["genres__title__in"] = genres_filters

        if artist_filters:
            kwargs["artist__title__in"] = artist_filters
        
        # if decade_filters:
        #     kwargs["release_date__range"] =  (decade_filters[0], int(decade_filters[0]) + 9)

        args = []

        # Multiple decades filtering
        if decade_filters:
            q = Q()
            for decade in decade_filters:
                start_year = decade
                end_year = int(decade) + 9
                q |= Q(release_date__range=(start_year, end_year))
                
            args.append(q) 

        print(args)
        print(kwargs)
        album = Album.objects.filter(
            *args,
            **kwargs).order_by('pk' if not sort_query else sort_query).distinct()
        return album


class AlbumSearchView(ArtistsGenresDataMixin, generic.ListView):
    model = Album
    context_object_name = 'albums'
    template_name = 'albums/albums_list.html'
    
    def get_queryset(self):
        query = self.request.GET.get("q")

        object_list = Album.objects.filter(
            Q(title__icontains=query) |
            Q(artist__title__icontains=query)
            ).order_by('artist', 'title')
        
        return object_list
    
# Admin views


# Albums
class AlbumCreateView(AdminRequiredMixin, GetModelNameMixin, generic.CreateView):
    template_name = "albums/album_create.html"
    form_class = AlbumModelForm
    
    def get_success_url(self):
        return reverse("admin-panel:albums-data")


class AlbumDeleteView(AdminRequiredMixin, GetModelNameMixin, generic.DeleteView):
    template_name = "albums/album_delete.html"
    model = Album
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:albums-data")


class AlbumUpdateView(AdminRequiredMixin, GetModelNameMixin, generic.UpdateView):
    template_name = "albums/album_update.html"
    form_class = AlbumModelForm
    model = Album
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:albums-data")


# Genres
class GenreCreateView(AdminRequiredMixin, GetModelNameMixin, generic.CreateView):
    template_name = "albums/album_create.html"
    form_class = GenreModelForm
    
    def get_success_url(self):
        return reverse("admin-panel:genres-data")


class GenreDeleteView(AdminRequiredMixin, GetModelNameMixin, generic.DeleteView):
    template_name = "albums/album_delete.html"
    model = Genre
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:genres-data")


class GenreUpdateView(AdminRequiredMixin, GetModelNameMixin, generic.UpdateView):
    template_name = "albums/album_update.html"
    form_class = GenreModelForm
    model = Genre
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:genres-data")


# Artists
class ArtistCreateView(AdminRequiredMixin, GetModelNameMixin, generic.CreateView):
    template_name = "albums/album_create.html"
    form_class = ArtistModelForm
    
    def get_success_url(self):
        return reverse("admin-panel:artists-data")


class ArtistDeleteView(AdminRequiredMixin, GetModelNameMixin, generic.DeleteView):
    template_name = "albums/album_delete.html"
    model = Artist
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:artists-data")


class ArtistUpdateView(AdminRequiredMixin, GetModelNameMixin, generic.UpdateView):
    template_name = "albums/album_update.html"
    form_class = ArtistModelForm
    model = Artist
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:artists-data")
    

albums/templates/albums/album_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}

<div id="album-create-page">
    <div>
        <h1>Add new {{model_name}}</h1>
    </div>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type='submit'>
            Submit
        </button>
    </form>
</div>

{% endblock content %}

albums/templates/albums/album_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div id="album-delete-page">
    <h1>Are you sure you want to delete this {{model_name}}?</h1>
    <form method="post" >
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Submit</button>
    </form>
</div>

{% endblock content %}

albums/templates/albums/album_detail.html
{% extends "base.html" %}

{% block content %}

<div id="album-page">
    <div id="album-image">
        <img src="{{ album.image }}" alt="{{ album.title }} cover image">

    </div>

    <div id="album-info">
        <h1>{{ album.title }} ({{ album.release_date }})</h1>
        <h2>{{ album.artist.title }}</h2>
        <p class="genres">
            {% for genre in album.genres.all %}
            <span class="genre">{{ genre.title }}</span>
            {% endfor %}
        </p>
        <p class="duration"><strong>Duration:</strong> {{ album.duration }}</p>
        <p class="tracks"><strong>Tracks:</strong></h3>
        <ol>
            {% for track in album.tracks %}
            <li>{{ track }}</li>
            {% endfor %}
        </ol>
        <p class="price"><strong>Price:</strong> {{ album.price }}.00 UAH</p>

        <div id="album-cart">
            {# Check if this item is already in cart#}
            {% if cart_item %}
            <a href="{% url 'orders:cart' %}">
                <button {% if not request.user.is_authenticated %} disabled="" {% endif %}>
                    View in cart
                </button>
            </a>
            {% else %}
            <form action="{% url 'orders:cart-item-create' %}" method="post">
                {% csrf_token %}
                {# Passing album primary key in POST request#}
                <input type="hidden" name="album_pk" value="{{ album.pk }}">

                <div>
                    <input type="number" min="1" name="quantity" max="1000" value="1">
                    <button type="submit" {% if not request.user.is_authenticated %} disabled="" {% endif %}>Add to cart</button>
                    {% if not request.user.is_authenticated %}
                    <p>You have to log in to buy this album</p>
                    {% endif %}
                </div>
            </form>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

albums/templates/albums/album_update.html
{% extends "base.html" %}

{% block content %}

<div id="album-update-page">
        <h1>Update "{{ model.title }}" {{model_name}} </h1>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'>
            Update
        </button>
    </form>
</div>

{% endblock content %}

albums/templates/albums/albums_list.html
{% extends "base.html" %}

{% block content %}
<div>
    {% include 'includes/sidebar.html' %}
    <div id="albums-list">
        {% for album in albums %}
        <div class="album">
            <a href="{% url 'albums:album-detail' album.pk %}">
                <img src="{{ album.image }}" alt="{{ album.title }}" class="album-image">
                <h3 class="album-title">{{ album.title }}</h3>
            </a>
            <p class="album-artist">{{ album.artist.title }}</p>
            <p class="album-price">Price: <span class="price">{{ album.price }} UAH</span></p>
        </div>
        {% endfor %}
        {% include 'includes/pagination.html' %}
    </div>
</div>

{% endblock content %}

albums/templates/albums/base.html
<html>
  <head>
    <title>Based albums shop</title>
  </head>
  <body>
    <div>
      {% block content %}
      {% endblock content %}
    </div>
  </body>
</html>