albums/urls.py
from django.urls import path

from .views import (AlbumListView, AlbumDetailView, AlbumFilterView, AlbumSearchView,
                    AlbumCreateView, AlbumUpdateView, AlbumDeleteView, GenreCreateView,
                    GenreUpdateView, GenreDeleteView, ArtistDeleteView, ArtistCreateView,
                    ArtistUpdateView)

app_name = 'albums'

urlpatterns = [
    # User endpoints (only albums)
    path('', AlbumListView.as_view(), name='albums-list'),
    path('filter/', AlbumFilterView.as_view(), name='albums-filter'),
    path('search/', AlbumSearchView.as_view(), name='albums-search'),
    
    # Admin endpoint (should be before album-detail to avoid errors)
    path('create/', AlbumCreateView.as_view(), name='album-create'),
    path('<pk>/', AlbumDetailView.as_view(), name='album-detail'),
    
    # Admin endpoints

    # Albums
    path('<pk>/update/', AlbumUpdateView.as_view(), name='album-update'),
    path('<pk>/delete/', AlbumDeleteView.as_view(), name='album-delete'),

    # Genres
    path('genres/create/', GenreCreateView.as_view(), name='genre-create'),
    path('genres/<pk>/update/', GenreUpdateView.as_view(), name='genre-update'),
    path('genres/<pk>/delete/', GenreDeleteView.as_view(), name='genre-delete'),

    # Artists
    path('artists/create/', ArtistCreateView.as_view(), name='artist-create'),
    path('artists/<pk>/update/', ArtistUpdateView.as_view(), name='artist-update'),
    path('artists/<pk>/delete/', ArtistDeleteView.as_view(), name='artist-delete'),
]

orders/urls.py
from django.urls import path

from .views import (CartView, cart_item_create_view, cart_item_remove_view,
                    order_create_view, order_pay_view, order_success_pay_view,
                    order_confirm_view, order_discard_view, user_ban_view, user_unban_view)

app_name = 'orders'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/', cart_item_create_view, name='cart-item-create'),
    path('delete/', cart_item_remove_view, name='cart-item-remove'),
    path('users/ban/<str:username>/', user_ban_view, name='user-ban'),
    path('users/unban/<str:username>/', user_unban_view, name='user-unban'),
    path('orders/', order_create_view, name='order-create'),
    path('orders/<int:pk>/pay/', order_pay_view, name='order-pay'),
    path('orders/<int:pk>/confirm/', order_confirm_view, name='order-confirm'),
    path('orders/<int:pk>/discard/', order_discard_view, name='order-discard'),
    path('orders/<int:pk>/pay/success/', order_success_pay_view, name='order-success-pay'),
]

website/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from albums.views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('albums/', include('albums.urls')),
    path('admin-panel/', include('admin_panel.urls')),
    path('cart/', include('orders.urls')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

orders/models.py
from django.contrib.auth.models import AbstractUser, User
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from albums.models import Album


class CustomUser(AbstractUser):
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _("username"),
        max_length=150,
        primary_key=True,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )
    is_banned = models.BooleanField(default=False)


class CartItem(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)


class Order(models.Model):
    user = models.ForeignKey(CustomUser, null=True, on_delete=models.SET_NULL)
    total_price = models.PositiveIntegerField()
    is_paid = models.BooleanField(default=False)
    is_confirmed = models.BooleanField(default=False)
    albums = models.ManyToManyField(db_table='OrderAlbum', to=Album)
    created_at = models.DateTimeField(auto_now_add=True)

orders/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden, HttpResponseNotAllowed
from django.shortcuts import redirect, render, get_object_or_404
from django.views import generic


from .models import CartItem, Order, CustomUser
from albums.models import Album


class CartView(LoginRequiredMixin, generic.ListView):
    template_name = 'orders/cart.html'
    context_object_name = 'cart_items'

    def get_queryset(self):
        user = self.request.user
        return CartItem.objects.filter(user=user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['unpaid_order'] = Order.objects.filter(user=self.request.user, is_paid=False)
        return context


def order_create_view(request):
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        total_price = request.POST.get('total_price')

        cart_items = [item['album_id'] for item in CartItem.objects.filter(user=request.user).values('album_id')]
        albums = Album.objects.filter(pk__in=cart_items)

        order = Order.objects.create(user=request.user, total_price=total_price)
        order.albums.set(albums)

        return redirect('orders:order-pay', pk=order.pk)
    else:
        return HttpResponseNotAllowed(['POST'])


def order_pay_view(request, pk):
    if not request.user.is_authenticated:
        return HttpResponseForbidden()

    order = get_object_or_404(Order, pk=pk)
    if request.user != order.user:
        return HttpResponseForbidden()

    if order.is_paid:
        return redirect('albums:albums-list')

    return render(request, 'orders/order_pay.html', context={'pk': pk})


def order_success_pay_view(request, pk):
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        order = get_object_or_404(Order, pk=pk)
        order.is_paid = True
        order.save()

        # Clean cart
        CartItem.objects.filter(user=request.user).delete()
        return render(request, 'orders/order_success_pay.html')
    else:
        return HttpResponseNotAllowed(['POST'])


def order_confirm_view(request, pk):
    if request.method == 'POST':
        if not request.user.is_authenticated or not request.user.is_staff:
            return HttpResponseForbidden()
        order = get_object_or_404(Order, pk=pk)
        order.is_confirmed = True
        order.save()

        return redirect('admin-panel:unconfirmed-orders')
    else:
        return HttpResponseNotAllowed(['POST'])


def order_discard_view(request, pk):
    if request.method == 'POST':
        if not request.user.is_authenticated or not request.user.is_staff:
            return HttpResponseForbidden()
        order = get_object_or_404(Order, pk=pk)
        order.delete()

        return redirect('admin-panel:unconfirmed-orders')
    else:
        return HttpResponseNotAllowed(['POST'])


def cart_item_create_view(request):
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return HttpResponseForbidden()

        album_pk = request.POST.get('album_pk')
        quantity = request.POST.get('quantity')
        album = get_object_or_404(Album, pk=album_pk)

        CartItem.objects.get_or_create(user=request.user, album=album, quantity=quantity)
        return redirect('albums:album-detail', pk=album_pk)
    else:
        return HttpResponseNotAllowed(['POST'])


def cart_item_remove_view(request):
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return HttpResponseForbidden()

        item_pk = request.POST.get('item_pk')

        CartItem.objects.filter(user=request.user, pk=item_pk).delete()
        return redirect('orders:cart')
    else:
        return HttpResponseNotAllowed(['POST'])


def user_ban_view(request, username):
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return HttpResponseForbidden()

        user = get_object_or_404(CustomUser, username=username)
        user.is_banned = True
        user.save()
        return redirect('admin-panel:unconfirmed-orders')
    else:
        return HttpResponseNotAllowed(['POST'])


def user_unban_view(request, username):
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return HttpResponseForbidden()

        user = get_object_or_404(CustomUser, username=username)
        user.is_banned = False
        user.save()
        return redirect('admin-panel:blacklist')
    else:
        return HttpResponseNotAllowed(['POST'])

orders/templates/orders/cart.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block content %}
<div id="cart-page">
    <h1>Your сart</h1>
    {% if not cart_items %}
    <h2>Your cart is empty</h2>
    {% else %}
    <table>
        <tbody>
            {% for item in cart_items %}
            <tr>
                <td class="image"><img src="{{ item.album.image }}"></td>
                <td class="album"><a href="{% url 'albums:album-detail' item.album.pk %}">{{ item.album.title }}</a></td>
                <td class="artist">{{ item.album.artist }}</td>
                <td class="price">{{ item.album.price }}.00 UAH</td>
                <td class="quantity">{{ item.quantity }}</td>
                <td class="remove">
                    <form action="{% url 'orders:cart-item-remove' %}" method="post">
                        <input type="hidden" name="item_pk" value="{{ item.pk }}">
                        {% csrf_token %}
                        <button>Remove from cart</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h2>Total price:
        {% with total_price=cart_items|calculate_total %}
        <b>{{ total_price }}.00 UAH</b>
    </h2>
    <form action="{% url 'orders:order-create' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="total_price" value="{{ total_price }}">
        <button id="order" type="submit" {% if unpaid_order %} disabled="" {% endif %}>
            Make an order</button>
        {% if unpaid_order %}
        <p style="color: red">You can't make new orders until you pay for the previous one</p>
        {% endif %}
    </form>
    {% endwith %}
    {% if unpaid_order %}
    <h2>Unpaid order: </h2>
    <a href="{% url 'orders:order-pay' unpaid_order.first.pk %}">Order</a>
    {% endif %}
    {% endif %}

</div>
{% endblock content %}

orders/templates/orders/order_pay.html
{% extends 'base.html' %}

{% block content %}
<div id="order-pay-page">
    <h1>Order was successfully created!</h1>
    <form action="{% url 'orders:order-success-pay' pk %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="order" value="{{ order }}">
        <button type="submit">Pay an order</button>
    </form>

</div>
{% endblock content %}

orders/templates/orders/order_success_pay.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div id="order-success-pay-page">
    <h1>Order was successfully paid!</h1>
    <p>Administrator will soon confirm it</p>
    <img src="{% static 'images/patrick-bateman.gif' %}" alt="">
    <a href="{% url 'albums:albums-list' %}"><button>Return to main page</button></a>
</div>{% endblock content %}