admin_panel/urls.py
from django.urls import path

from .views import (MainView, AlbumsDataView, GenresDataView,
                    ArtistsDataView, AlbumsDataSearchView, UnconfirmedOrdersDataView,
                    ConfirmedOrdersDataView, UsersBlacklistView)

app_name = 'admin-panel'

urlpatterns = [
    path('', MainView.as_view(), name='main-page'),
    path('albums/', AlbumsDataView.as_view(), name='albums-data'),
    path('albums/search/', AlbumsDataSearchView.as_view(), name='albums-data-search'),
    path('genres/', GenresDataView.as_view(), name='genres-data'),
    path('artists/', ArtistsDataView.as_view(), name='artists-data'),
    path('blacklist/', UsersBlacklistView.as_view(), name='blacklist'),
    path('unconfirmed-orders/', UnconfirmedOrdersDataView.as_view(), name='unconfirmed-orders'),
    path('confirmed-orders/', ConfirmedOrdersDataView.as_view(), name='confirmed-orders'),
]

albums/urls.py
from django.urls import path

from .views import (AlbumListView, AlbumDetailView, AlbumFilterView, AlbumSearchView,
                    AlbumCreateView, AlbumUpdateView, AlbumDeleteView, GenreCreateView,
                    GenreUpdateView, GenreDeleteView, ArtistDeleteView, ArtistCreateView,
                    ArtistUpdateView)

app_name = 'albums'

urlpatterns = [
    # User endpoints (only albums)
    path('', AlbumListView.as_view(), name='albums-list'),
    path('filter/', AlbumFilterView.as_view(), name='albums-filter'),
    path('search/', AlbumSearchView.as_view(), name='albums-search'),
    
    # Admin endpoint (should be before album-detail to avoid errors)
    path('create/', AlbumCreateView.as_view(), name='album-create'),
    path('<pk>/', AlbumDetailView.as_view(), name='album-detail'),
    
    # Admin endpoints

    # Albums
    path('<pk>/update/', AlbumUpdateView.as_view(), name='album-update'),
    path('<pk>/delete/', AlbumDeleteView.as_view(), name='album-delete'),

    # Genres
    path('genres/create/', GenreCreateView.as_view(), name='genre-create'),
    path('genres/<pk>/update/', GenreUpdateView.as_view(), name='genre-update'),
    path('genres/<pk>/delete/', GenreDeleteView.as_view(), name='genre-delete'),

    # Artists
    path('artists/create/', ArtistCreateView.as_view(), name='artist-create'),
    path('artists/<pk>/update/', ArtistUpdateView.as_view(), name='artist-update'),
    path('artists/<pk>/delete/', ArtistDeleteView.as_view(), name='artist-delete'),
]

orders/urls.py
from django.urls import path

from .views import (CartView, cart_item_create_view, cart_item_remove_view,
                    order_create_view, order_pay_view, order_success_pay_view,
                    order_confirm_view, order_discard_view, user_ban_view, user_unban_view)

app_name = 'orders'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/', cart_item_create_view, name='cart-item-create'),
    path('delete/', cart_item_remove_view, name='cart-item-remove'),
    path('users/ban/<str:username>/', user_ban_view, name='user-ban'),
    path('users/unban/<str:username>/', user_unban_view, name='user-unban'),
    path('orders/', order_create_view, name='order-create'),
    path('orders/<int:pk>/pay/', order_pay_view, name='order-pay'),
    path('orders/<int:pk>/confirm/', order_confirm_view, name='order-confirm'),
    path('orders/<int:pk>/discard/', order_discard_view, name='order-discard'),
    path('orders/<int:pk>/pay/success/', order_success_pay_view, name='order-success-pay'),
]

website/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from albums.views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('albums/', include('albums.urls')),
    path('admin-panel/', include('admin_panel.urls')),
    path('cart/', include('orders.urls')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

albums/models.py
from django.db import models

from .validators import validate_text, validate_release_date


class GenreArtistManager(models.Manager):
    def get_ordered_by_title(self):
        return self.all().order_by('title')


class Artist(models.Model):
    title = models.CharField(max_length=75, validators=[validate_text])

    objects = GenreArtistManager()

    def __str__(self) -> str:
        return self.title


class Genre(models.Model):
    title = models.CharField(max_length=75, validators=[validate_text])
    
    objects = GenreArtistManager()
    
    def __str__(self) -> str:
        return self.title


class Album(models.Model):
    # General fields
    title = models.CharField(max_length=75, validators=[validate_text])
    release_date = models.CharField(max_length=30, blank=True, validators=[validate_release_date])
    duration = models.CharField(max_length=10, blank=True)
    image = models.URLField()    
    tracks = models.JSONField()
    price = models.IntegerField()
    count = models.IntegerField(default=10000)

    # One-to-many fields
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

    # Many-to-many fields
    genres = models.ManyToManyField(Genre, db_table='AlbumsGenres')

    def __str__(self) -> str:
        return self.title 
    

albums/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField

from .models import Album, Genre, Artist
from orders.models import CustomUser


class AlbumModelForm(forms.ModelForm):
    duration = forms.DurationField(widget=forms.TextInput(attrs={'placeholder': ''}))
    tracks = forms.CharField(label="Tracks",
                             widget=forms.Textarea())
    genres = forms.ModelMultipleChoiceField(
            widget=forms.SelectMultiple(),
            queryset=Genre.objects.get_ordered_by_title(),
            required=True,
        )
    artist = forms.ModelChoiceField(queryset=Artist.objects.get_ordered_by_title(),
                                    required=True)

    class Meta:
        model = Album
        fields = (
            'title',
            'release_date',
            'duration',
            'image',
            'tracks',
            'price',
            'genres',
            'artist',
        )

    def clean_title(self):
        title = self.cleaned_data.get('title')
        album = Album.objects.filter(title__iexact=title).exists()
        if album:
            raise forms.ValidationError('Альбом з такою назвою вже існує')
        return title

    def clean(self):
        cleaned_data = super().clean()

        # Convert tracks string into list
        tracks = cleaned_data.get('tracks')
        tracks_list = [track for track in tracks.split('\r\n')]
        cleaned_data['tracks'] = tracks_list

        return cleaned_data


class GenreModelForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ['title']

    def clean_title(self):
        title = self.cleaned_data.get('title')
        album = Genre.objects.filter(title__iexact=title).exists()
        if album:
            raise forms.ValidationError('Жанр з такою назвою вже існує')
        return title


class ArtistModelForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ['title']

    def clean_title(self):
        title = self.cleaned_data.get('title')
        album = Artist.objects.filter(title__iexact=title).exists()
        if album:
            raise forms.ValidationError('Артист з таким ім\'ям уже існує')
        return title


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username",)
        field_classes = {'username': UsernameField}

    # def clean_username(self):
    #     username = self.cleaned_data.get("username")
    #     if CustomUser.objects.filter(username=username).exists():
    #         raise forms.ValidationError(
    #             "This username is already in use"
    #         )
    #     return username

albums/views.py
from typing import Any

from django.db.models.query import QuerySet
from django.urls import reverse
from django.views import generic
from django.db.models import Q

from .models import Album, Genre, Artist
from .forms import AlbumModelForm, ArtistModelForm, GenreModelForm, CustomUserCreationForm
from .mixins import ArtistsGenresDataMixin, GetModelNameMixin, AdminRequiredMixin
from orders.models import CartItem, Order


# Additional view to add context data to filter sidebar
# User views

class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def form_valid(self, form):
        response = super().form_valid(form)
        return response

    def get_success_url(self):
        return reverse("login")


class AlbumListView(ArtistsGenresDataMixin, generic.ListView):
    model = Album
    template_name = 'albums/albums_list.html'
    context_object_name = 'albums'


class AlbumDetailView(generic.DetailView):
    model = Album
    template_name = 'albums/album_detail.html'
    context_object_name = 'album'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_item'] = CartItem.objects.filter(user=self.request.user, album__pk=context['album'].pk)
        return context


class AlbumFilterView(ArtistsGenresDataMixin, generic.ListView):
    context_object_name = 'albums'
    template_name = 'albums/albums_list.html'

    def get_queryset(self) -> QuerySet[Any]:

        # Retrieving 'True' checkboxes' values from fort GET request
        genres_filters = self.request.GET.getlist("genre")
        artist_filters = self.request.GET.getlist("artist")
        decade_filters = self.request.GET.getlist("decades")

        sort_query = self.request.GET.get('sort_by')

        # Condition to prevent hand-written query parametrs in link
        allowed_sort_queries = ['price', '-price', 'release_date', '-release_date']
        if sort_query not in allowed_sort_queries:
            sort_query = None

        kwargs = {}
        if genres_filters: 
            kwargs["genres__title__in"] = genres_filters

        if artist_filters:
            kwargs["artist__title__in"] = artist_filters
        
        # if decade_filters:
        #     kwargs["release_date__range"] =  (decade_filters[0], int(decade_filters[0]) + 9)

        args = []

        # Multiple decades filtering
        if decade_filters:
            q = Q()
            for decade in decade_filters:
                start_year = decade
                end_year = int(decade) + 9
                q |= Q(release_date__range=(start_year, end_year))
                
            args.append(q) 

        print(args)
        print(kwargs)
        album = Album.objects.filter(
            *args,
            **kwargs).order_by('pk' if not sort_query else sort_query).distinct()
        return album


class AlbumSearchView(ArtistsGenresDataMixin, generic.ListView):
    model = Album
    context_object_name = 'albums'
    template_name = 'albums/albums_list.html'
    
    def get_queryset(self):
        query = self.request.GET.get("q")

        object_list = Album.objects.filter(
            Q(title__icontains=query) |
            Q(artist__title__icontains=query)
            ).order_by('artist', 'title')
        
        return object_list
    
# Admin views


# Albums
class AlbumCreateView(AdminRequiredMixin, GetModelNameMixin, generic.CreateView):
    template_name = "albums/album_create.html"
    form_class = AlbumModelForm
    
    def get_success_url(self):
        return reverse("admin-panel:albums-data")


class AlbumDeleteView(AdminRequiredMixin, GetModelNameMixin, generic.DeleteView):
    template_name = "albums/album_delete.html"
    model = Album
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:albums-data")


class AlbumUpdateView(AdminRequiredMixin, GetModelNameMixin, generic.UpdateView):
    template_name = "albums/album_update.html"
    form_class = AlbumModelForm
    model = Album
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:albums-data")


# Genres
class GenreCreateView(AdminRequiredMixin, GetModelNameMixin, generic.CreateView):
    template_name = "albums/album_create.html"
    form_class = GenreModelForm
    
    def get_success_url(self):
        return reverse("admin-panel:genres-data")


class GenreDeleteView(AdminRequiredMixin, GetModelNameMixin, generic.DeleteView):
    template_name = "albums/album_delete.html"
    model = Genre
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:genres-data")


class GenreUpdateView(AdminRequiredMixin, GetModelNameMixin, generic.UpdateView):
    template_name = "albums/album_update.html"
    form_class = GenreModelForm
    model = Genre
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:genres-data")


# Artists
class ArtistCreateView(AdminRequiredMixin, GetModelNameMixin, generic.CreateView):
    template_name = "albums/album_create.html"
    form_class = ArtistModelForm
    
    def get_success_url(self):
        return reverse("admin-panel:artists-data")


class ArtistDeleteView(AdminRequiredMixin, GetModelNameMixin, generic.DeleteView):
    template_name = "albums/album_delete.html"
    model = Artist
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:artists-data")


class ArtistUpdateView(AdminRequiredMixin, GetModelNameMixin, generic.UpdateView):
    template_name = "albums/album_update.html"
    form_class = ArtistModelForm
    model = Artist
    context_object_name = 'model'

    def get_success_url(self):
        return reverse("admin-panel:artists-data")
    

albums/templates/includes/navbar.html
{% load static %}
<header>
  <a href="{% url 'albums:albums-list' %}">
    <div id="header-logo">
      Vinyl Store
    </div>
  </a>

  {% if not request.user.is_authenticated %}
  <div id="header-signup">
    <a href="{% url 'signup' %}">Signup</a>
  </div>
  {% endif %}

  {% if not request.user.is_authenticated %}
  <div id="header-login">
    <a href="{% url 'login' %}">
      Login
    </a>
  </div>
  {% endif %}

  {% if request.user.is_authenticated %}
  <div id="header-logged">
    <p>Logged in as: <i>{{ request.user.username }}</i></p>
    <a href="{% url 'logout' %}" style="text-decoration: underline;">
      Logout
    </a>
  </div>
  {% endif %}

  {% if request.user.is_authenticated %}
  <a href="{% url 'orders:cart' %}">
    <div id="header-cart">
      <img src="{% static 'images/cart.png' %}" alt="">
      Cart
    </div>
  </a>
  {% endif %}

  {% if request.user.is_staff %}
  <a href="{% url 'admin-panel:main-page' %}">
    <div id="header-admin-panel">
      Admin panel
    </div>
  </a>
  {% endif %}

</header>

albums/templates/includes/pagination.html
{% load static %}
{% load spurl %}
{% if page_obj.has_other_pages %}
<div class="album-pagination">
  <nav class="album-pagination-list">
    {% if page_obj.number|add:-1 > 0 %}
    <a href="{% spurl query=request.GET set_query='page={{ page_obj.number|add:-1 }}' %}" aria-label="Previous">
      <span aria-hidden="true">&laquo;</span>
    </a>
    {% endif %}
    {% for p in paginator.page_range %}
    {% if page_obj.number == p %}
    <a class="active">{{ p }}</a>
    {% else %}
    {% if 'sort_by' in request.get_full_path %}
    <a href="{% spurl query=request.GET set_query='page={{ p }}' %}">{{ p }}</a>
    {% else %}
    <a href="{% spurl query=request.GET set_query='page={{ p }}' %}">{{ p }}</a>
    {% endif %}
    {% endif %}
    {% endfor %}
    {% if page_obj.number|add:1 <= paginator.num_pages %} <a
      href="{% spurl query=request.GET set_query='page={{ page_obj.number|add:1 }}' %}" aria-label="Next">
      <span aria-hidden="true">&raquo;</span>
      {% endif %}
      </a>
  </nav>
</div>
{% endif %}

albums/templates/includes/sidebar.html
<div id="sidebar">
    <div class="sidebar-elem" id="search">
        <h2>Search</h2>
        <form action="{% url 'albums:albums-search' %}" method="get" id="form-search">
            <input type="text" name="q">
            <button type="submit">Search</button>
        </form>
        <hr>
    </div>

    <div class="sidebar-elem" id="sort">
        <h2>Sort by</h2>
        <form action="{% url 'albums:albums-filter' %}" method="get">
            <h3>Price</h3>
            <input type="radio" value="price" name="sort_by">
            <label for="increase">Ascending</label><br>
            <input type="radio" value="-price" name="sort_by">
            <label for="decrease">Descending</label>
            <br>

            <h3>Release date</h3>
            <input type="radio" value="release_date" name="sort_by">
            <label for="increase">Ascending</label><br>
            <input type="radio" value="-release_date" name="sort_by">
            <label for="decrease">Descending</label>
            <br>
            <button type="submit">Sort</button>
        </form>
        <hr>
    </div>

    <div class="sidebar-elem" id="filter">
        <form action="{% url 'albums:albums-filter' %}" method="get">
            <div>
                <h2>Filter by</h2>
                <h3>Decades</h3>
                <ul>
                    {% for year in view.get_decades_range %}
                    <li>
                        <input type="checkbox" name="decades" value="{{ year }}"> {{ year }}s
                    </li>
                    {% endfor %}
                </ul>
                <h3>Genres</h3>
                <ul>
                    {% for genre in view.get_genres %}
                    <li>
                        <input type="checkbox" name="genre" value="{{ genre.title }}">
                        <span>{{genre.title}}</span>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div>
                <h3>Artists</h3>
                <ul>
                    {% for artist in view.get_artists %}
                    <li>
                        <input type="checkbox" name="artist" value="{{ artist.title }}">
                        <span>{{artist.title}}</span>
                    </li>
                    {% endfor %}
                </ul>
                <button type="submit">Search</button>
            </div>
        </form>

    </div>
</div>